import type { Country, City, Activity } from "./types";

export const COUNTRIES: Country[] = [
  {
    id: "c-morocco",
    slug: "morocco",
    name: "Morocco",
    nameI18n: { fr: "Maroc", es: "Marruecos", it: "Marocco" },
    flag: "🇲🇦",
    displayOrder: 1,
  },
];

export const CITIES: City[] = [
  { id: "ci-marrakech",   countryId: "c-morocco", slug: "marrakech",   name: "Marrakech",   nameI18n: { fr: "Marrakech", es: "Marrakech", it: "Marrakech" },       heroImage: "/images/morocco/marrakech.jpg",     displayOrder: 1 },
  { id: "ci-fes",         countryId: "c-morocco", slug: "fes",         name: "Fès",         nameI18n: { fr: "Fès", es: "Fez", it: "Fès" },                         heroImage: "/images/morocco/fes.jpg",           displayOrder: 2 },
  { id: "ci-chefchaouen", countryId: "c-morocco", slug: "chefchaouen", name: "Chefchaouen", nameI18n: { fr: "Chefchaouen", es: "Chefchaouen", it: "Chefchaouen" }, heroImage: "/images/morocco/chefchaouen.jpg",   displayOrder: 3 },
  { id: "ci-casablanca",  countryId: "c-morocco", slug: "casablanca",  name: "Casablanca",  nameI18n: { fr: "Casablanca", es: "Casablanca", it: "Casablanca" },                                                    displayOrder: 4 },
  { id: "ci-rabat",       countryId: "c-morocco", slug: "rabat",       name: "Rabat",       nameI18n: { fr: "Rabat", es: "Rabat", it: "Rabat" },                   heroImage: "/images/morocco/rabat.jpg",         displayOrder: 5 },
  { id: "ci-tangier",     countryId: "c-morocco", slug: "tangier",     name: "Tangier",     nameI18n: { fr: "Tanger", es: "Tánger", it: "Tangeri" },                                                               displayOrder: 6 },
  { id: "ci-agadir",      countryId: "c-morocco", slug: "agadir",      name: "Agadir",      nameI18n: { fr: "Agadir", es: "Agadir", it: "Agadir" },                                                                displayOrder: 7 },
  { id: "ci-essaouira",   countryId: "c-morocco", slug: "essaouira",   name: "Essaouira",   nameI18n: { fr: "Essaouira", es: "Esauira", it: "Essaouira" },         heroImage: "/images/morocco/essaouira.jpg",     displayOrder: 8 },
  { id: "ci-merzouga",    countryId: "c-morocco", slug: "merzouga",    name: "Merzouga",    nameI18n: { fr: "Merzouga", es: "Merzouga", it: "Merzouga" },           heroImage: "/images/morocco/sahara-desert.jpg", displayOrder: 9 },
  { id: "ci-ouarzazate",  countryId: "c-morocco", slug: "ouarzazate",  name: "Ouarzazate",  nameI18n: { fr: "Ouarzazate", es: "Uarzazat", it: "Ouarzazate" },                                                      displayOrder: 10 },
];

export const ACTIVITIES: Activity[] = [
  {
    id: "viator-fes-115777P9",
    cityId: "ci-fes",
    slug: "fez-to-marrakech-merzouga-desert-tour",
    title: "Best Fez to Marrakech via Merzouga Desert Dunes, 3 Days Tour",
    titleI18n: {},
    descI18n: {},
    category: "day-trip",
    platform: "viator",
    affiliateUrl: "https://www.viator.com/Fez/d22151-ttd/p-115777P9?pid=P00306218&mcid=42383&medium=link&medium_version=selector&campaign=citytaste-mer&source=shortlink&localeSwitch=1",
    imageUrl: "/images/offers/viator-fes-115777P9.jpg",
    priceFrom: 244,
    currency: "USD",
    duration: "3 days",
    priority: 1,
  },
  {
    id: "viator-fes-463193P2",
    cityId: "ci-fes",
    slug: "fez-medina-walking-tour",
    title: "Exclusive Fez Medina Walking Tour with Private Guide",
    titleI18n: {},
    descI18n: {},
    category: "medina-tour",
    platform: "viator",
    affiliateUrl: "https://www.viator.com/Fez/d22151-ttd/p-463193P2?pid=P00306218&mcid=42383&medium=link&medium_version=selector&campaign=citytaste-dbgh&source=shortlink&localeSwitch=1",
    imageUrl: "/images/offers/viator-fes-463193P2.jpg",
    priceFrom: 36,
    currency: "USD",
    duration: "4 hours",
    priority: 1,
  },
  {
    id: "viator-fes-459799P6",
    cityId: "ci-fes",
    slug: "fez-pottery-mosaic-workshop",
    title: "Pottery and Mosaic Workshop in Fes Led by Local Artisans",
    titleI18n: {},
    descI18n: {},
    category: "activity",
    platform: "viator",
    affiliateUrl: "https://www.viator.com/Fez/d22151-ttd/p-459799P6?pid=P00306218&mcid=42383&medium=link&medium_version=selector&campaign=citytaste-tin&source=shortlink&localeSwitch=1",
    imageUrl: "/images/offers/viator-fes-459799P6.jpg",
    priceFrom: 45,
    currency: "USD",
    duration: "2 hours",
    priority: 1,
  },
  {
    id: "viator-marrakech-104348P1",
    cityId: "ci-marrakech",
    slug: "marrakech-hot-air-balloon",
    title: "Hot Air Balloon Flight over Marrakech with Traditional Breakfast",
    titleI18n: {},
    descI18n: {},
    category: "activity",
    platform: "viator",
    affiliateUrl: "https://www.viator.com/tours/Marrakech/Hot-Air-Balloon-Flight-over-Marrakech-with-Traditional-Breakfast/d5408-104348P1?pid=P00306218&mcid=42383&medium=link&medium_version=selector&campaign=citytaste-minta",
    imageUrl: "/images/offers/viator-marrakech-104348P1.jpg",
    priceFrom: 106,
    currency: "USD",
    duration: "4-5 hours",
    priority: 1,
  },
  {
    id: "viator-marrakech-25014P1",
    cityId: "ci-marrakech",
    slug: "marrakech-atlas-mountains-3-valleys",
    title: "Full-Day Trip from Marrakech to the Atlas Mountains, 3 Valleys through Berber Villages",
    titleI18n: {},
    descI18n: {},
    category: "day-trip",
    platform: "viator",
    affiliateUrl: "https://www.viator.com/tours/Marrakech/Full-Day-Trip-from-Marrakech-to-the-Atlas-Mountains-3-Valleys-through-Berber-Villages/d5408-25014P1?pid=P00306218&mcid=42383&medium=link&medium_version=selector&campaign=citytaste-atla",
    imageUrl: "/images/offers/viator-marrakech-25014P1.jpg",
    priceFrom: 93,
    currency: "USD",
    duration: "7-8 hours",
    priority: 1,
  },
  {
    id: "viator-marrakech-261757P5",
    cityId: "ci-marrakech",
    slug: "marrakech-atlas-agafay-desert",
    title: "Atlas Mountains and Agafay Desert and Berber Village Full-Day Trip From Marrakech",
    titleI18n: {},
    descI18n: {},
    category: "day-trip",
    platform: "viator",
    affiliateUrl: "https://www.viator.com/tours/Marrakech/Atlas-Mountains-and-Agafay-Desert-and-Berber-Village-Full-Day-Trip-From-Marrakech/d5408-261757P5?pid=P00306218&mcid=42383&medium=link&medium_version=selector&campaign=citytaste-agafa",
    imageUrl: "/images/offers/viator-marrakech-261757P5.jpg",
    priceFrom: 26,
    currency: "USD",
    duration: "5 hours",
    priority: 1,
  },
  {
    id: "viator-marrakech-71659P5",
    cityId: "ci-marrakech",
    slug: "marrakech-agafay-quad-camel-dinner",
    title: "Agafay Desert Package: Quad Bike, Camel Ride and Dinner Show",
    titleI18n: {},
    descI18n: {},
    category: "activity",
    platform: "viator",
    affiliateUrl: "https://www.viator.com/tours/Marrakech/Day-trip-from-Marrakech-to-berber-villages-and-UNESCO-Kasbahs-from-Marrakech/d5408-71659P5?pid=P00306218&mcid=42383&medium=link&medium_version=selector&campaign=citytaste-quad",
    imageUrl: "/images/offers/viator-marrakech-71659P5.jpg",
    priceFrom: 35,
    currency: "USD",
    duration: "6-7 hours",
    priority: 2,
  },
  {
    id: "viator-marrakech-112810P1",
    cityId: "ci-marrakech",
    slug: "marrakech-cooking-class",
    title: "Moroccan Cooking Class in Marrakech with Market Tour",
    titleI18n: {},
    descI18n: {},
    category: "cooking-class",
    platform: "viator",
    affiliateUrl: "https://www.viator.com/tours/Marrakech/Cooking-class-with-chef-Leila/d5408-112810P1?pid=P00306218&mcid=42383&medium=link&medium_version=selector&campaign=citytaste-cui",
    imageUrl: "/images/offers/viator-marrakech-112810P1.jpg",
    priceFrom: 44,
    currency: "USD",
    duration: "3-4 hours",
    priority: 2,
  },
  {
    id: "viator-marrakech-237009P3",
    cityId: "ci-marrakech",
    slug: "marrakech-balloon-quad-experience",
    title: "Hot Air Balloon Ride with Berber Breakfast and Quad Biking Experience",
    titleI18n: {},
    descI18n: {},
    category: "activity",
    platform: "viator",
    affiliateUrl: "https://www.viator.com/tours/Marrakech/Hot-Air-Balloon-Ride-with-Berber-Breakfast-and-Quad-Experience/d5408-237009P3?pid=P00306218&mcid=42383&medium=link&medium_version=selector&campaign=citytaste-mint",
    imageUrl: "/images/offers/viator-marrakech-237009P3.jpg",
    priceFrom: 80,
    currency: "USD",
    duration: "6-7 hours",
    priority: 2,
  },
];
