/**
 * Image manifest — maps place slug → local WebP image paths.
 * Auto-generated by scripts/image-pipeline.ts — do not edit manually.
 * Run: npx tsx scripts/image-pipeline.ts
 */
import type { PlaceImageData } from "./types";

let _manifest: Record<string, PlaceImageData> | null = null;

function loadManifest(): Record<string, PlaceImageData> {
  if (_manifest) return _manifest;
  try {
    // eslint-disable-next-line @typescript-eslint/no-require-imports
    _manifest = require("../public/images/places/manifest.json") as Record<
      string,
      PlaceImageData
    >;
  } catch {
    _manifest = {};
  }
  return _manifest;
}

export function getPlaceImages(slug: string): PlaceImageData | null {
  return loadManifest()[slug] ?? null;
}

export function hasLocalImages(slug: string): boolean {
  return getPlaceImages(slug) !== null;
}

export function getAllManifestSlugs(): string[] {
  return Object.keys(loadManifest());
}
