import type { Place } from "./types";

const img = (id: string) =>
  `https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=800&q=80`;

export const mockPlaces: Place[] = [
  // ─── PARIS PÂTISSERIES ────────────────────────────────────────────────────────
  {
    id: "paris-pierre-herme",
    citySlug: "paris",
    name: "Pierre Hermé",
    slug: "pierre-herme",
    categories: ["patisseries"],
    address: "72 Rue Bonaparte, 75006 Paris",
    neighborhood: "Saint-Germain-des-Prés / 6e",
    rating: 4.8,
    reviewCount: 2140,
    priceLevel: 3,
    lat: 48.8527,
    lng: 2.3329,
    phone: "+33 1 43 54 47 77",
    website: "https://www.pierreherme.com",
    googleMapsUrl: "https://maps.google.com/?q=Pierre+Hermé+72+Rue+Bonaparte+Paris",
    photos: [
      img("1414235077428-338989a2e8c0"),
      img("1555396273-367ea4eb4db5"),
      img("1540189549336-e6e99c3679fe"),
    ],
    openingHours: {
      Monday: "10:00 – 19:00",
      Tuesday: "10:00 – 19:00",
      Wednesday: "10:00 – 19:00",
      Thursday: "10:00 – 19:00",
      Friday: "10:00 – 19:00",
      Saturday: "10:00 – 19:30",
      Sunday: "10:00 – 19:00",
    },
    isHalal: false,
    isFamilyFriendly: true,
    hasTerrace: false,
    description:
      "The Picasso of pastry. Pierre Hermé revolutionised the macaron and elevated French pâtisserie to haute couture. His Saint-Germain boutique is a pilgrimage site for sweet lovers worldwide, famed for the iconic Ispahan — rose, lychee and raspberry — alongside daring seasonal collections.",
    reviewSummary:
      "Guests unanimously call it the most creative pastry shop in Paris. The Ispahan macaron is celebrated as life-changing. Premium prices are justified by extraordinary quality; a boxed assortment makes the ultimate Paris souvenir.",
    reviews: [
      { id: "ph-r1", author: "Clara M.", rating: 5, text: "The Ispahan is simply the best thing I've ever eaten. Worth every euro.", date: "2025-03-10", initials: "CM" },
      { id: "ph-r2", author: "Thomas W.", rating: 5, text: "Incredible seasonal variety. Don't skip the chocolates — they're as good as the macarons.", date: "2025-02-14", initials: "TW" },
      { id: "ph-r3", author: "Ana R.", rating: 4, text: "Expensive but extraordinary. The packaging alone is a work of art.", date: "2025-01-20", initials: "AR" },
    ],
  },
  {
    id: "paris-laduree",
    citySlug: "paris",
    name: "Ladurée",
    slug: "laduree",
    categories: ["patisseries"],
    address: "75 Avenue des Champs-Élysées, 75008 Paris",
    neighborhood: "Champs-Élysées / 8e",
    rating: 4.7,
    reviewCount: 3850,
    priceLevel: 3,
    lat: 48.8726,
    lng: 2.3035,
    phone: "+33 1 40 75 08 75",
    website: "https://www.laduree.fr",
    googleMapsUrl: "https://maps.google.com/?q=Ladurée+Champs-Élysées+Paris",
    photos: [
      img("1555396273-367ea4eb4db5"),
      img("1414235077428-338989a2e8c0"),
      img("1466978913421-dad2ebd01d17"),
    ],
    openingHours: {
      Monday: "09:00 – 20:00",
      Tuesday: "09:00 – 20:00",
      Wednesday: "09:00 – 20:00",
      Thursday: "09:00 – 20:00",
      Friday: "09:00 – 20:00",
      Saturday: "09:00 – 21:00",
      Sunday: "09:00 – 20:00",
    },
    isHalal: false,
    isFamilyFriendly: true,
    hasTerrace: true,
    description:
      "The house that invented the double-decker macaron in 1930. Ladurée's Champs-Élysées salon is a Parisian institution draped in pastel green and gilded Napoléon III decor. Beyond macarons, the salon de thé serves light lunches and afternoon teas in true Parisian grandeur.",
    reviewSummary:
      "Visitors love the iconic setting as much as the macarons. The afternoon tea experience is considered quintessentially Parisian. Queues can be long on weekends — arriving early or ordering online for pickup is strongly recommended.",
    reviews: [
      { id: "ld-r1", author: "Sophie B.", rating: 5, text: "The real Parisian experience. Sat in the salon for afternoon tea — utterly magical.", date: "2025-04-01", initials: "SB" },
      { id: "ld-r2", author: "Mark J.", rating: 4, text: "Classic macarons, beautiful decor. Pricey but you're paying for the whole experience.", date: "2025-02-20", initials: "MJ" },
      { id: "ld-r3", author: "Léa F.", rating: 5, text: "Rose and salted caramel macarons are divine. The gift boxes are perfection.", date: "2025-01-15", initials: "LF" },
    ],
  },
  {
    id: "paris-du-pain-des-idees",
    citySlug: "paris",
    name: "Du Pain et des Idées",
    slug: "du-pain-et-des-idees",
    categories: ["patisseries", "cafes"],
    address: "34 Rue Yves Toudic, 75010 Paris",
    neighborhood: "Canal Saint-Martin / 10e",
    rating: 4.9,
    reviewCount: 1620,
    priceLevel: 2,
    lat: 48.8692,
    lng: 2.3616,
    phone: "+33 1 42 40 44 52",
    googleMapsUrl: "https://maps.google.com/?q=Du+Pain+et+des+Idées+Paris",
    photos: [
      img("1466978913421-dad2ebd01d17"),
      img("1540189549336-e6e99c3679fe"),
      img("1555396273-367ea4eb4db5"),
    ],
    openingHours: {
      Monday: "Closed",
      Tuesday: "07:00 – 20:00",
      Wednesday: "07:00 – 20:00",
      Thursday: "07:00 – 20:00",
      Friday: "07:00 – 20:00",
      Saturday: "07:00 – 20:00",
      Sunday: "Closed",
    },
    isHalal: false,
    isFamilyFriendly: true,
    hasTerrace: false,
    description:
      "Rated among the best bakeries in the world, this Canal Saint-Martin gem is housed in a stunning 1889 Napoléon III boulangerie. Christophe Vasseur's pain des amis loaf and escargots feuilletés are worth a detour from anywhere in Paris. Arrive early — the best items sell out by 10am.",
    reviewSummary:
      "Regulars queue from opening for the escargot pastries and the flaky pain des amis. The historic interior is stunningly preserved. Most guests say it's the single best baked good they've eaten in Paris.",
    reviews: [
      { id: "dpdi-r1", author: "Hugo P.", rating: 5, text: "The pistachio escargot is the best pastry I've ever had. I went back three days in a row.", date: "2025-03-22", initials: "HP" },
      { id: "dpdi-r2", author: "Alice N.", rating: 5, text: "Incredible bread, beautiful old-school boulangerie. Get there before 9am.", date: "2025-02-05", initials: "AN" },
      { id: "dpdi-r3", author: "Raj K.", rating: 5, text: "Worth the Canal Saint-Martin detour. The croissants are somehow better than anywhere else.", date: "2025-01-30", initials: "RK" },
    ],
  },
  {
    id: "paris-cyril-lignac",
    citySlug: "paris",
    name: "Cyril Lignac Pâtisserie",
    slug: "cyril-lignac",
    categories: ["patisseries"],
    address: "24 Rue Paul Bert, 75011 Paris",
    neighborhood: "Bastille / 11e",
    rating: 4.8,
    reviewCount: 980,
    priceLevel: 3,
    lat: 48.8549,
    lng: 2.3775,
    phone: "+33 1 43 67 21 18",
    website: "https://www.gourmand-croquant.com",
    googleMapsUrl: "https://maps.google.com/?q=Cyril+Lignac+24+Rue+Paul+Bert+Paris",
    photos: [
      img("1551218808-94e220e084d2"),
      img("1414235077428-338989a2e8c0"),
      img("1567620832903-9fc6debc209f"),
    ],
    openingHours: {
      Monday: "Closed",
      Tuesday: "08:30 – 19:30",
      Wednesday: "08:30 – 19:30",
      Thursday: "08:30 – 19:30",
      Friday: "08:30 – 19:30",
      Saturday: "08:30 – 19:30",
      Sunday: "08:30 – 19:30",
    },
    isHalal: false,
    isFamilyFriendly: true,
    hasTerrace: false,
    description:
      "TV chef and chocolatier Cyril Lignac brings Michelin-star sensibility to neighbourhood pâtisserie. His Équinoxe tart — caramel, chocolate, coffee — has become a Paris cult object. The Bastille boutique is intimate and the queue is a testament to the quality.",
    reviewSummary:
      "The Équinoxe tart gets the most mentions — guests describe it as perfectly balanced and impossibly rich. The small-batch production means freshness is unrivalled. Weekend queues are long but move quickly.",
    reviews: [
      { id: "cl-r1", author: "Emma T.", rating: 5, text: "The Équinoxe tart is a religious experience. Chocolate, caramel, coffee — perfect harmony.", date: "2025-04-08", initials: "ET" },
      { id: "cl-r2", author: "David L.", rating: 5, text: "Finally made it here after months of planning. Lived up to every bit of the hype.", date: "2025-03-15", initials: "DL" },
      { id: "cl-r3", author: "Nadia C.", rating: 4, text: "Excellent pastries. The éclair au chocolat is the best I've found in Paris.", date: "2025-02-28", initials: "NC" },
    ],
  },
  {
    id: "paris-stohrer",
    citySlug: "paris",
    name: "Stohrer",
    slug: "stohrer",
    categories: ["patisseries"],
    address: "51 Rue Montorgueil, 75002 Paris",
    neighborhood: "Montorgueil / 2e",
    rating: 4.7,
    reviewCount: 1380,
    priceLevel: 2,
    lat: 48.8623,
    lng: 2.3480,
    phone: "+33 1 42 33 38 20",
    website: "https://www.stohrer.fr",
    googleMapsUrl: "https://maps.google.com/?q=Stohrer+51+Rue+Montorgueil+Paris",
    photos: [
      img("1567620832903-9fc6debc209f"),
      img("1466978913421-dad2ebd01d17"),
      img("1555396273-367ea4eb4db5"),
    ],
    openingHours: {
      Monday: "07:30 – 20:30",
      Tuesday: "07:30 – 20:30",
      Wednesday: "07:30 – 20:30",
      Thursday: "07:30 – 20:30",
      Friday: "07:30 – 20:30",
      Saturday: "07:30 – 20:30",
      Sunday: "07:30 – 20:00",
    },
    isHalal: false,
    isFamilyFriendly: true,
    hasTerrace: false,
    description:
      "Paris's oldest pâtisserie, founded in 1730 by Nicolas Stohrer, pastry chef to King Louis XV. The baroque interior — painted ceilings, gilded mirrors — is a classified historic monument. Stohrer invented the rum baba; sampling one here is tasting living history.",
    reviewSummary:
      "Visitors are awed by the historic interior as much as the pastries. The rum baba is considered unmissable — authentic, boozy and perfectly done. Staff are knowledgeable about the 300-year history and happy to explain each creation.",
    reviews: [
      { id: "st-r1", author: "Isabelle M.", rating: 5, text: "The most beautiful pâtisserie interior in Paris. The rum baba is extraordinary — drenched in good rum.", date: "2025-03-05", initials: "IM" },
      { id: "st-r2", author: "Ben H.", rating: 5, text: "History and taste in equal measure. The puits d'amour custard tart is incredible.", date: "2025-01-18", initials: "BH" },
      { id: "st-r3", author: "Cécile D.", rating: 4, text: "A Paris institution. The prices are reasonable for the quality and the atmosphere is unmatched.", date: "2024-12-10", initials: "CD" },
    ],
  },

  // ─── PARIS MONUMENTS ──────────────────────────────────────────────────────────
  {
    id: "paris-tour-eiffel",
    citySlug: "paris",
    name: "Tour Eiffel",
    slug: "tour-eiffel",
    categories: ["monuments"],
    address: "Champ de Mars, 5 Avenue Anatole France, 75007 Paris",
    neighborhood: "Champ de Mars / 7e",
    rating: 4.9,
    reviewCount: 142000,
    priceLevel: 2,
    lat: 48.8584,
    lng: 2.2945,
    website: "https://www.toureiffel.paris",
    bookingUrl: "https://www.toureiffel.paris/fr/les-billets",
    googleMapsUrl: "https://maps.google.com/?q=Tour+Eiffel+Paris",
    entryPrice: "€29.40",
    duration: "2–3 hours",
    photos: [
      img("1484723091739-30acba28bc29"),
      img("1502602898657-3e91760cbb34"),
      img("1445116572660-236099ec97a0"),
    ],
    openingHours: {
      Monday: "09:00 – 24:00",
      Tuesday: "09:00 – 24:00",
      Wednesday: "09:00 – 24:00",
      Thursday: "09:00 – 24:00",
      Friday: "09:00 – 24:00",
      Saturday: "09:00 – 24:00",
      Sunday: "09:00 – 24:00",
    },
    isHalal: false,
    isFamilyFriendly: true,
    hasTerrace: true,
    description:
      "The defining symbol of Paris. Gustave Eiffel's 1889 iron lattice tower soars 330 metres and welcomes seven million visitors a year. Take the lift to the summit for 360° views stretching to the horizon — particularly spectacular at dusk when the city turns golden, and magical after dark when the tower sparkles every hour.",
    reviewSummary:
      "Guests consistently call the summit view a once-in-a-lifetime experience. The evening light show is universally loved. Pre-booking timed tickets online is essential — walk-up queues can exceed two hours.",
    reviews: [
      { id: "te-r1", author: "Yuki S.", rating: 5, text: "Went at dusk and stayed for the light show. The summit view left me speechless.", date: "2025-04-10", initials: "YS" },
      { id: "te-r2", author: "Carlos V.", rating: 5, text: "Book the summit tickets well in advance. Absolutely worth it — Paris from above is breathtaking.", date: "2025-03-22", initials: "CV" },
      { id: "te-r3", author: "Priya N.", rating: 5, text: "The sparkling lights at night are magical. Our kids were completely awestruck.", date: "2025-02-14", initials: "PN" },
    ],
    featured: true,
  },
  {
    id: "paris-louvre",
    citySlug: "paris",
    name: "Musée du Louvre",
    slug: "musee-du-louvre",
    categories: ["monuments", "museums"],
    address: "Rue de Rivoli, 75001 Paris",
    neighborhood: "1er Arrondissement",
    rating: 4.8,
    reviewCount: 98000,
    priceLevel: 2,
    lat: 48.8606,
    lng: 2.3376,
    website: "https://www.louvre.fr",
    bookingUrl: "https://www.louvre.fr/visites/billets-coupe-file",
    googleMapsUrl: "https://maps.google.com/?q=Musée+du+Louvre+Paris",
    entryPrice: "€22",
    duration: "3–4 hours",
    photos: [
      img("1445116572660-236099ec97a0"),
      img("1504674900247-0877df9cc836"),
      img("1504754524776-8f4f37790ca0"),
    ],
    openingHours: {
      Monday: "09:00 – 18:00",
      Tuesday: "Closed",
      Wednesday: "09:00 – 21:45",
      Thursday: "09:00 – 18:00",
      Friday: "09:00 – 21:45",
      Saturday: "09:00 – 18:00",
      Sunday: "09:00 – 18:00",
    },
    isHalal: false,
    isFamilyFriendly: true,
    hasTerrace: false,
    description:
      "The world's largest art museum and a historic monument, housing over 35,000 works across 72,000 square metres of galleries. Home to the Mona Lisa, Venus de Milo and Winged Victory of Samothrace. The I.M. Pei glass pyramid entrance is itself an iconic piece of modern architecture.",
    reviewSummary:
      "Visitors agree you need at least a full day — or several visits — to do it justice. The Mona Lisa gallery is always crowded; arriving at opening or visiting on Wednesday/Friday evenings offers a calmer experience. The Egyptian antiquities and Denon wing sculptures are frequently cited as highlights.",
    reviews: [
      { id: "lv-r1", author: "Amanda L.", rating: 5, text: "Spent an entire day and only covered a fraction. The Denon wing sculptures alone are worth the price.", date: "2025-04-05", initials: "AL" },
      { id: "lv-r2", author: "Stefan K.", rating: 5, text: "Go on a Friday evening — far fewer crowds, magical atmosphere. The Mona Lisa is surprisingly small but the surrounding art is extraordinary.", date: "2025-03-14", initials: "SK" },
      { id: "lv-r3", author: "Mei W.", rating: 4, text: "Book skip-the-line tickets. The queues without them can be over an hour.", date: "2025-02-28", initials: "MW" },
    ],
  },
  {
    id: "paris-notre-dame",
    citySlug: "paris",
    name: "Notre-Dame de Paris",
    slug: "notre-dame-de-paris",
    categories: ["monuments"],
    address: "6 Parvis Notre-Dame, Pl. Jean-Paul II, 75004 Paris",
    neighborhood: "Île de la Cité / 4e",
    rating: 4.9,
    reviewCount: 87000,
    priceLevel: 0,
    lat: 48.8530,
    lng: 2.3499,
    website: "https://www.notredamedeparis.fr",
    googleMapsUrl: "https://maps.google.com/?q=Notre-Dame+de+Paris",
    entryPrice: "Free",
    duration: "1–2 hours",
    photos: [
      img("1495474472287-4d71bcdd2085"),
      img("1502602898657-3e91760cbb34"),
      img("1484723091739-30acba28bc29"),
    ],
    openingHours: {
      Monday: "08:00 – 19:00",
      Tuesday: "08:00 – 19:00",
      Wednesday: "08:00 – 19:00",
      Thursday: "08:00 – 19:00",
      Friday: "08:00 – 19:00",
      Saturday: "08:00 – 19:00",
      Sunday: "08:00 – 19:00",
    },
    isHalal: false,
    isFamilyFriendly: true,
    hasTerrace: false,
    description:
      "Paris's most beloved Gothic cathedral, fully reopened in December 2024 after the devastating 2019 fire. The five-year restoration has returned Notre-Dame to its full glory — the rose windows glow with recovered colour, the nave soars with renewed grandeur, and the rebuilt spire once again crowns the Île de la Cité skyline.",
    reviewSummary:
      "Visitors describe the reopened cathedral as more beautiful than before the fire. The restored interior has a luminous quality that moves people to tears. Entry is free but reservations are required and fill up weeks in advance.",
    reviews: [
      { id: "nd-r1", author: "Françoise M.", rating: 5, text: "Wept when I walked in. The restoration is miraculous — it glows. Reserve your slot weeks ahead.", date: "2025-04-12", initials: "FM" },
      { id: "nd-r2", author: "Tom G.", rating: 5, text: "Even more beautiful than before the fire. The light through the restored rose windows is extraordinary.", date: "2025-03-30", initials: "TG" },
      { id: "nd-r3", author: "Sara P.", rating: 5, text: "Book well in advance — free entry but slots go fast. Absolutely worth the effort.", date: "2025-03-10", initials: "SP" },
    ],
    featured: true,
  },
  {
    id: "paris-arc-de-triomphe",
    citySlug: "paris",
    name: "Arc de Triomphe",
    slug: "arc-de-triomphe",
    categories: ["monuments"],
    address: "Place Charles de Gaulle, 75008 Paris",
    neighborhood: "Champs-Élysées / 8e",
    rating: 4.7,
    reviewCount: 56000,
    priceLevel: 2,
    lat: 48.8738,
    lng: 2.2950,
    website: "https://www.paris-arc-de-triomphe.fr",
    bookingUrl: "https://www.paris-arc-de-triomphe.fr/en/practical-info/tickets",
    googleMapsUrl: "https://maps.google.com/?q=Arc+de+Triomphe+Paris",
    entryPrice: "€13",
    duration: "1 hour",
    photos: [
      img("1559339352-11d035aa65de"),
      img("1502602898657-3e91760cbb34"),
      img("1484723091739-30acba28bc29"),
    ],
    openingHours: {
      Monday: "10:00 – 23:00",
      Tuesday: "10:00 – 23:00",
      Wednesday: "10:00 – 23:00",
      Thursday: "10:00 – 23:00",
      Friday: "10:00 – 23:00",
      Saturday: "10:00 – 23:00",
      Sunday: "10:00 – 23:00",
    },
    isHalal: false,
    isFamilyFriendly: true,
    hasTerrace: true,
    description:
      "Napoléon's triumphal arch stands at the head of the Champs-Élysées where twelve grand avenues radiate outward in a star formation. Climb the 284 steps to the rooftop terrace for a dramatic panorama of Paris — the Eiffel Tower to the west, Sacré-Cœur to the north, La Défense beyond the horizon.",
    reviewSummary:
      "The rooftop view looking down the Champs-Élysées is cited as one of the best vistas in Paris. Sunset visits are especially recommended. Take the underpass to reach the monument — do not attempt to cross the roundabout on foot.",
    reviews: [
      { id: "adt-r1", author: "Lars B.", rating: 5, text: "The view down the Champs-Élysées at sunset is one of the great Paris sights. Totally worth the climb.", date: "2025-04-02", initials: "LB" },
      { id: "adt-r2", author: "Maria S.", rating: 4, text: "Great views from the top. The reliefs on the arch itself are also incredibly detailed — allow time to study them.", date: "2025-02-20", initials: "MS" },
      { id: "adt-r3", author: "James T.", rating: 5, text: "Underrated compared to the Eiffel Tower — shorter queues, equally amazing views.", date: "2025-01-25", initials: "JT" },
    ],
  },
  {
    id: "paris-sainte-chapelle",
    citySlug: "paris",
    name: "Sainte-Chapelle",
    slug: "sainte-chapelle",
    categories: ["monuments"],
    address: "8 Boulevard du Palais, 75001 Paris",
    neighborhood: "Île de la Cité / 1er",
    rating: 4.8,
    reviewCount: 42000,
    priceLevel: 2,
    lat: 48.8554,
    lng: 2.3450,
    website: "https://www.sainte-chapelle.fr",
    bookingUrl: "https://www.sainte-chapelle.fr/en/visit/book-a-ticket",
    googleMapsUrl: "https://maps.google.com/?q=Sainte-Chapelle+Paris",
    entryPrice: "€13",
    duration: "1 hour",
    photos: [
      img("1482049016688-2d3e1b311543"),
      img("1504674900247-0877df9cc836"),
      img("1504754524776-8f4f37790ca0"),
    ],
    openingHours: {
      Monday: "09:00 – 17:00",
      Tuesday: "09:00 – 17:00",
      Wednesday: "09:00 – 17:00",
      Thursday: "09:00 – 21:00",
      Friday: "09:00 – 17:00",
      Saturday: "09:00 – 17:00",
      Sunday: "09:00 – 17:00",
    },
    isHalal: false,
    isFamilyFriendly: true,
    hasTerrace: false,
    description:
      "A Gothic jewel box on the Île de la Cité. Built in 1248 by King Louis IX to house the Crown of Thorns, Sainte-Chapelle contains 1,113 stained glass panels telling the story of the Bible in extraordinary colour and detail. When sunlight floods the upper chapel, it is among the most transcendent architectural experiences in France.",
    reviewSummary:
      "The stained glass is universally described as jaw-dropping — visitors say no photo does it justice. The upper chapel in morning light is considered one of the most beautiful interiors in the world. Book in advance to avoid long queues at security.",
    reviews: [
      { id: "sc-r1", author: "Claire H.", rating: 5, text: "Nothing prepares you for the upper chapel. The glass is overwhelming in the best possible way.", date: "2025-04-14", initials: "CH" },
      { id: "sc-r2", author: "Dario M.", rating: 5, text: "The most beautiful interior I have ever seen. Go on a sunny morning for the full effect.", date: "2025-03-08", initials: "DM" },
      { id: "sc-r3", author: "Nina W.", rating: 5, text: "Tiny but absolutely breathtaking. One of the true wonders of Paris — don't miss it.", date: "2025-02-10", initials: "NW" },
    ],
  },

  // ─── PARIS ACTIVITIES ─────────────────────────────────────────────────────────
  {
    id: "paris-bateaux-mouches",
    citySlug: "paris",
    name: "Seine Cruise — Bateaux Mouches",
    slug: "bateaux-mouches",
    categories: ["activities"],
    address: "Port de la Conférence, Pont de l'Alma, 75008 Paris",
    neighborhood: "Alma / 8e",
    rating: 4.6,
    reviewCount: 28000,
    priceLevel: 2,
    lat: 48.8632,
    lng: 2.3101,
    website: "https://www.bateaux-mouches.fr",
    bookingUrl: "https://www.bateaux-mouches.fr/fr/reservations",
    googleMapsUrl: "https://maps.google.com/?q=Bateaux+Mouches+Paris",
    entryPrice: "€17",
    duration: "1 hour",
    photos: [
      img("1522336572468-97b06e8ef143"),
      img("1502602898657-3e91760cbb34"),
      img("1484723091739-30acba28bc29"),
    ],
    openingHours: {
      Monday: "10:00 – 22:30",
      Tuesday: "10:00 – 22:30",
      Wednesday: "10:00 – 22:30",
      Thursday: "10:00 – 22:30",
      Friday: "10:00 – 22:30",
      Saturday: "10:00 – 22:30",
      Sunday: "10:00 – 22:30",
    },
    isHalal: false,
    isFamilyFriendly: true,
    hasTerrace: true,
    description:
      "The classic way to discover Paris from the water. Bateaux Mouches glass-roofed boats glide past Notre-Dame, the Eiffel Tower, the Musée d'Orsay and dozens of other monuments on a 1-hour guided cruise. Evening departures offer stunning illuminated views of the Eiffel Tower light show.",
    reviewSummary:
      "Guests love the ease and the unique perspective on Paris landmarks. The evening cruise is widely preferred — seeing the Eiffel Tower sparkle from the river is unforgettable. Bring a light jacket even in summer as the river can be breezy.",
    reviews: [
      { id: "bm-r1", author: "Rachel K.", rating: 5, text: "The evening cruise was magical — the Eiffel Tower from the water at night is a memory I'll keep forever.", date: "2025-04-06", initials: "RK" },
      { id: "bm-r2", author: "Pierre A.", rating: 4, text: "Great introduction to Paris. The audio guide is informative. Evening departure is the way to go.", date: "2025-03-20", initials: "PA" },
      { id: "bm-r3", author: "Hina O.", rating: 4, text: "Relaxing and scenic. My kids loved waving at people on the bridges. Sit on the right side going out for best Eiffel Tower views.", date: "2025-02-18", initials: "HO" },
    ],
  },
  {
    id: "paris-cordon-bleu",
    citySlug: "paris",
    name: "Le Cordon Bleu — Cooking Class",
    slug: "le-cordon-bleu",
    categories: ["activities"],
    address: "13-15 Quai André Citroën, 75015 Paris",
    neighborhood: "15e Arrondissement",
    rating: 4.8,
    reviewCount: 3200,
    priceLevel: 4,
    lat: 48.8462,
    lng: 2.2972,
    website: "https://www.cordonbleu.edu/paris",
    bookingUrl: "https://www.cordonbleu.edu/paris/demonstration-classes",
    googleMapsUrl: "https://maps.google.com/?q=Le+Cordon+Bleu+Paris",
    entryPrice: "€150",
    duration: "3 hours",
    photos: [
      img("1550547660-d9450f859349"),
      img("1414235077428-338989a2e8c0"),
      img("1555396273-367ea4eb4db5"),
    ],
    openingHours: {
      Monday: "09:00 – 18:00",
      Tuesday: "09:00 – 18:00",
      Wednesday: "09:00 – 18:00",
      Thursday: "09:00 – 18:00",
      Friday: "09:00 – 18:00",
      Saturday: "09:00 – 18:00",
      Sunday: "Closed",
    },
    isHalal: false,
    isFamilyFriendly: false,
    hasTerrace: false,
    description:
      "Learn classic French technique from world-class chefs at the most famous culinary school on earth. Demonstration and hands-on classes cover everything from croissant lamination to coq au vin to advanced pâtisserie. Conducted in English and French with simultaneous translation — no prior experience required for introductory classes.",
    reviewSummary:
      "Guests describe it as the highlight of their Paris trip. The professional kitchen environment and expert instructors make participants feel like real chefs. The meal at the end — made by your own hands — is deeply satisfying. Book months in advance for popular classes.",
    reviews: [
      { id: "lcb-r1", author: "Jessica M.", rating: 5, text: "Best experience of my Paris trip by far. Made a proper coq au vin and soufflé. The instructor was incredible.", date: "2025-04-08", initials: "JM" },
      { id: "lcb-r2", author: "Oliver R.", rating: 5, text: "Worth every euro. The croissant class changed my understanding of pastry completely. Book way ahead.", date: "2025-02-12", initials: "OR" },
      { id: "lcb-r3", author: "Nathalie B.", rating: 4, text: "Professional, well-organised, delicious results. The demonstration classes are great value.", date: "2025-01-28", initials: "NB" },
    ],
  },
  {
    id: "paris-wine-tasting-marais",
    citySlug: "paris",
    name: "Wine Tasting Le Marais",
    slug: "wine-tasting-le-marais",
    categories: ["activities", "bars"],
    address: "11 Rue Saint-Gilles, 75003 Paris",
    neighborhood: "Le Marais / 3e",
    rating: 4.7,
    reviewCount: 1450,
    priceLevel: 3,
    lat: 48.8558,
    lng: 2.3534,
    website: "https://www.o-chateau.com",
    bookingUrl: "https://www.o-chateau.com/paris-wine-tastings",
    googleMapsUrl: "https://maps.google.com/?q=O+Chateau+Wine+Bar+Paris",
    entryPrice: "€45",
    duration: "2 hours",
    photos: [
      img("1565299624946-b28f40a0ae38"),
      img("1571091718767-18b5b1457add"),
      img("1565557623262-b51c2513a641"),
    ],
    openingHours: {
      Monday: "18:00 – 22:00",
      Tuesday: "18:00 – 22:00",
      Wednesday: "18:00 – 22:00",
      Thursday: "18:00 – 22:00",
      Friday: "18:00 – 23:00",
      Saturday: "14:00 – 23:00",
      Sunday: "14:00 – 20:00",
    },
    isHalal: false,
    isFamilyFriendly: false,
    hasTerrace: false,
    description:
      "Guided wine tastings in a historic Le Marais cave, led by passionate sommeliers from top Paris wine school O Château. Sessions cover six wines from different French regions with food pairings, entertaining storytelling and the inside knowledge to navigate French wine lists with confidence. Perfect for beginners and enthusiasts alike.",
    reviewSummary:
      "Guests leave feeling genuinely educated and thoroughly entertained. The sommeliers make complex wine accessible with humour. The Burgundy versus Bordeaux session is the most popular. A fun and social experience even if you arrive as a solo traveller.",
    reviews: [
      { id: "wt-r1", author: "Kevin D.", rating: 5, text: "Left knowing infinitely more about French wine — and with a healthy Burgundy obsession. Hugely fun.", date: "2025-04-10", initials: "KD" },
      { id: "wt-r2", author: "Simone G.", rating: 5, text: "The sommelier was hilarious and incredibly knowledgeable. Best value €45 I've spent in Paris.", date: "2025-03-18", initials: "SG" },
      { id: "wt-r3", author: "Paul M.", rating: 4, text: "Informative and social — met great people. The cheese pairings were spot on.", date: "2025-02-22", initials: "PM" },
    ],
  },
  {
    id: "paris-bike-tour",
    citySlug: "paris",
    name: "Bike Tour Paris",
    slug: "bike-tour-paris",
    categories: ["activities"],
    address: "24 Rue Edgar Faure, 75015 Paris",
    neighborhood: "Eiffel Tower / 15e",
    rating: 4.8,
    reviewCount: 5600,
    priceLevel: 2,
    lat: 48.8603,
    lng: 2.3477,
    website: "https://www.parisbiketour.com",
    bookingUrl: "https://www.parisbiketour.com/reservations",
    googleMapsUrl: "https://maps.google.com/?q=Paris+Bike+Tour+Eiffel+Tower",
    entryPrice: "€35",
    duration: "3 hours",
    photos: [
      img("1512058564366-18510be2db19"),
      img("1445116572660-236099ec97a0"),
      img("1502602898657-3e91760cbb34"),
    ],
    openingHours: {
      Monday: "10:00 – 18:00",
      Tuesday: "10:00 – 18:00",
      Wednesday: "10:00 – 18:00",
      Thursday: "10:00 – 18:00",
      Friday: "10:00 – 18:00",
      Saturday: "09:00 – 19:00",
      Sunday: "09:00 – 19:00",
    },
    isHalal: false,
    isFamilyFriendly: true,
    hasTerrace: false,
    description:
      "Discover Paris like a local on a guided 3-hour bicycle tour through the city's most iconic and hidden neighbourhoods. Small groups of maximum 12 cyclists explore the Latin Quarter, Île Saint-Louis, Le Marais, the Seine banks and the Eiffel Tower, with stops for photos and insider stories from knowledgeable local guides.",
    reviewSummary:
      "Guests consistently rate this among their top Paris experiences. The small group size means personal attention and flexibility. Morning tours are recommended for quieter streets. The guides' local knowledge transforms the city — guests discover hidden squares and stories they'd never find alone.",
    reviews: [
      { id: "bt-r1", author: "Lisa C.", rating: 5, text: "Best way to see Paris — our guide knew every hidden alley and story. Absolutely loved it.", date: "2025-04-09", initials: "LC" },
      { id: "bt-r2", author: "Sven A.", rating: 5, text: "Covered so much ground without exhausting ourselves. The morning light in Le Marais was beautiful.", date: "2025-03-25", initials: "SA" },
      { id: "bt-r3", author: "Yemi O.", rating: 5, text: "Relaxed pace, amazing guide, brilliant route. The Île Saint-Louis stop is a highlight.", date: "2025-02-15", initials: "YO" },
    ],
  },
  {
    id: "paris-fragonard-perfume",
    citySlug: "paris",
    name: "Fragonard Perfume Workshop",
    slug: "fragonard-perfume-workshop",
    categories: ["activities"],
    address: "9 Rue Scribe, 75009 Paris",
    neighborhood: "Opéra / 9e",
    rating: 4.6,
    reviewCount: 2800,
    priceLevel: 2,
    lat: 48.8735,
    lng: 2.3329,
    website: "https://www.fragonard.com/parfumeur/en/",
    bookingUrl: "https://www.fragonard.com/parfumeur/en/ateliers",
    googleMapsUrl: "https://maps.google.com/?q=Fragonard+Perfume+Paris",
    entryPrice: "€20",
    duration: "1 hour",
    photos: [
      img("1529006557810-274b9b2fc783"),
      img("1587314168485-3236d6710814"),
      img("1466978913421-dad2ebd01d17"),
    ],
    openingHours: {
      Monday: "09:00 – 18:00",
      Tuesday: "09:00 – 18:00",
      Wednesday: "09:00 – 18:00",
      Thursday: "09:00 – 18:00",
      Friday: "09:00 – 18:00",
      Saturday: "09:00 – 18:00",
      Sunday: "Closed",
    },
    isHalal: false,
    isFamilyFriendly: true,
    hasTerrace: false,
    description:
      "Create your own fragrance in a workshop led by Fragonard's master perfumers. This storied Grasse-born house — operating since 1926 — teaches participants the language of perfumery: top, heart and base notes, and how to blend them into a signature scent. You leave with your custom 50ml bottle, a uniquely Parisian souvenir.",
    reviewSummary:
      "Guests love the creative and personal nature of the experience. The instructors are expert and patient. The finished custom fragrance is considered the perfect Paris souvenir. Sessions fill up fast — advance booking recommended.",
    reviews: [
      { id: "fg-r1", author: "Sophie C.", rating: 5, text: "Created my own perfume — the most unique souvenir I've ever brought home. The instructor was fantastic.", date: "2025-04-03", initials: "SC" },
      { id: "fg-r2", author: "Alex T.", rating: 4, text: "Fascinating introduction to the art of perfume. My blended fragrance turned out surprisingly well!", date: "2025-03-12", initials: "AT" },
      { id: "fg-r3", author: "Mia L.", rating: 5, text: "Unexpectedly one of my favourite Paris activities. Fun, educational and I'll wear my creation forever.", date: "2025-02-08", initials: "ML" },
    ],
  },

  // ─── PARIS MARKETS ────────────────────────────────────────────────────────────
  {
    id: "paris-marche-aligre",
    citySlug: "paris",
    name: "Marché d'Aligre",
    slug: "marche-daligre",
    categories: ["markets"],
    address: "Place d'Aligre, 75012 Paris",
    neighborhood: "Bastille / 12e",
    rating: 4.7,
    reviewCount: 3100,
    priceLevel: 0,
    lat: 48.8495,
    lng: 2.3735,
    googleMapsUrl: "https://maps.google.com/?q=Marché+d'Aligre+Paris",
    entryPrice: "Free",
    photos: [
      img("1488459716781-f2de5cb440e1"),
      img("1573821663912-569905455b1c"),
      img("1551024506-0bccd828d307"),
    ],
    openingHours: {
      Monday: "Closed",
      Tuesday: "08:00 – 13:30",
      Wednesday: "08:00 – 13:30",
      Thursday: "08:00 – 13:30",
      Friday: "08:00 – 13:30",
      Saturday: "08:00 – 15:00",
      Sunday: "08:00 – 13:30",
    },
    isHalal: false,
    isFamilyFriendly: true,
    hasTerrace: false,
    description:
      "Paris's most authentic and affordable outdoor market, beloved by chefs and locals in equal measure. The Marché d'Aligre combines a colourful street market, a covered food hall (Marché Beauvau) and a brocante flea market in one vibrant square. Arrive early for the best produce and the electric atmosphere of old Paris.",
    reviewSummary:
      "Regulars call it the best market in Paris for genuine neighbourhood character. The prices are lower than other tourist-facing markets and the produce is exceptional. The adjacent covered hall offers cheese, charcuterie and wine. Go early on a Saturday for the full experience.",
    reviews: [
      { id: "ma-r1", author: "Bertrand F.", rating: 5, text: "The real Paris market experience. Great prices, superb produce, authentic crowd. My Saturday morning ritual.", date: "2025-04-12", initials: "BF" },
      { id: "ma-r2", author: "Helen D.", rating: 5, text: "Nothing touristy about this one. Bought the most incredible strawberries and goat's cheese.", date: "2025-03-29", initials: "HD" },
      { id: "ma-r3", author: "Marco V.", rating: 4, text: "Arrive before 9am to get the best selection. The flea market section is great for vintage finds too.", date: "2025-02-22", initials: "MV" },
    ],
  },
  {
    id: "paris-marche-enfants-rouges",
    citySlug: "paris",
    name: "Marché des Enfants Rouges",
    slug: "marche-des-enfants-rouges",
    categories: ["markets"],
    address: "39 Rue de Bretagne, 75003 Paris",
    neighborhood: "Le Marais / 3e",
    rating: 4.6,
    reviewCount: 4200,
    priceLevel: 0,
    lat: 48.8620,
    lng: 2.3606,
    googleMapsUrl: "https://maps.google.com/?q=Marché+des+Enfants+Rouges+Paris",
    entryPrice: "Free",
    photos: [
      img("1573821663912-569905455b1c"),
      img("1488459716781-f2de5cb440e1"),
      img("1517248135467-4c7edcad34c4"),
    ],
    openingHours: {
      Monday: "Closed",
      Tuesday: "08:30 – 13:00 · 16:00 – 19:30",
      Wednesday: "08:30 – 13:00 · 16:00 – 19:30",
      Thursday: "08:30 – 13:00 · 16:00 – 19:30",
      Friday: "08:30 – 13:00 · 16:00 – 19:30",
      Saturday: "08:30 – 13:00 · 16:00 – 19:30",
      Sunday: "08:30 – 14:00",
    },
    isHalal: false,
    isFamilyFriendly: true,
    hasTerrace: false,
    description:
      "Paris's oldest covered market, operating since 1628 in the heart of Le Marais. Under its beautiful iron and glass roof, vendors sell fresh produce alongside prepared food stalls offering Moroccan tajines, Japanese bento, Antillean creole cooking and classic French charcuterie. The communal tables fill up at lunchtime with a wonderfully diverse crowd.",
    reviewSummary:
      "Guests love the multicultural food stalls as much as the historic setting. The Moroccan stall and Japanese bento are consistently recommended. Arrive at 11am to beat the lunchtime rush and grab a communal table.",
    reviews: [
      { id: "mer-r1", author: "Fatima K.", rating: 5, text: "The best lunch spot in Le Marais. The Moroccan stall's couscous is incredible. Lively atmosphere under a beautiful old roof.", date: "2025-04-07", initials: "FK" },
      { id: "mer-r2", author: "Lucie P.", rating: 4, text: "Charming old market with fantastic international food stalls. Gets very busy on weekends — arrive early.", date: "2025-03-14", initials: "LP" },
      { id: "mer-r3", author: "Chris N.", rating: 5, text: "Hidden gem in Le Marais. The Japanese bento and the cheese stall are both unmissable.", date: "2025-02-28", initials: "CN" },
    ],
  },
  {
    id: "paris-marche-bastille",
    citySlug: "paris",
    name: "Marché Bastille",
    slug: "marche-bastille",
    categories: ["markets"],
    address: "Boulevard Richard-Lenoir, 75011 Paris",
    neighborhood: "Bastille / 11e",
    rating: 4.7,
    reviewCount: 2800,
    priceLevel: 0,
    lat: 48.8519,
    lng: 2.3694,
    googleMapsUrl: "https://maps.google.com/?q=Marché+Bastille+Paris",
    entryPrice: "Free",
    photos: [
      img("1551024506-0bccd828d307"),
      img("1488459716781-f2de5cb440e1"),
      img("1573821663912-569905455b1c"),
    ],
    openingHours: {
      Monday: "Closed",
      Tuesday: "Closed",
      Wednesday: "Closed",
      Thursday: "07:00 – 14:30",
      Friday: "Closed",
      Saturday: "Closed",
      Sunday: "07:00 – 14:30",
    },
    isHalal: false,
    isFamilyFriendly: true,
    hasTerrace: false,
    description:
      "One of Paris's largest and most lively open-air markets, stretching along the central canal of Boulevard Richard-Lenoir every Thursday and Sunday. Over 100 vendors sell exceptional produce, farm cheeses, fresh fish, organic breads and flowers. The Sunday market draws both neighbourhood locals doing their weekly shop and food-loving visitors.",
    reviewSummary:
      "The Sunday market is the standout — lively, large and full of excellent produce. The cheese and charcuterie stalls are particularly praised. The stretching canal setting with its tree-lined promenade makes this one of the most pleasant market experiences in the city.",
    reviews: [
      { id: "mb-r1", author: "Antoine L.", rating: 5, text: "Sunday morning at Bastille market followed by a canal-side picnic is my ideal Paris morning.", date: "2025-04-13", initials: "AL" },
      { id: "mb-r2", author: "Grace H.", rating: 4, text: "Enormous variety and excellent quality. The farm cheese stall was exceptional. Great atmosphere.", date: "2025-03-23", initials: "GH" },
      { id: "mb-r3", author: "Tomás R.", rating: 5, text: "Better than the tourist-heavy markets. Real Parisian life at its best. Great prices too.", date: "2025-02-16", initials: "TR" },
    ],
  },
  {
    id: "paris-puces-saint-ouen",
    citySlug: "paris",
    name: "Puces de Saint-Ouen",
    slug: "puces-de-saint-ouen",
    categories: ["markets"],
    address: "Rue des Rosiers, 93400 Saint-Ouen",
    neighborhood: "Saint-Ouen / Porte de Clignancourt",
    rating: 4.5,
    reviewCount: 12000,
    priceLevel: 0,
    lat: 48.9033,
    lng: 2.3451,
    website: "https://www.marcheauxpuces-saintouen.com",
    googleMapsUrl: "https://maps.google.com/?q=Marché+aux+Puces+Saint-Ouen",
    entryPrice: "Free",
    photos: [
      img("1482049016688-2d3e1b311543"),
      img("1551024506-0bccd828d307"),
      img("1517248135467-4c7edcad34c4"),
    ],
    openingHours: {
      Monday: "11:00 – 17:00",
      Tuesday: "Closed",
      Wednesday: "Closed",
      Thursday: "Closed",
      Friday: "Closed",
      Saturday: "09:00 – 18:00",
      Sunday: "10:00 – 18:00",
    },
    isHalal: false,
    isFamilyFriendly: true,
    hasTerrace: false,
    description:
      "The world's largest antiques market, covering 7 hectares and comprising 15 distinct covered and open-air markets. From museum-quality 18th-century furniture and vintage Hermès scarves to mid-century design, vinyl records and African art — the Puces de Saint-Ouen is an all-day treasure hunt. Serious dealers and casual browsers happily coexist.",
    reviewSummary:
      "Visitors recommend coming with a loose agenda and comfortable shoes — the scale is vast and wonderful. Saturday is the prime day for the widest selection. Bargaining is expected and enjoyed. The covered Marché Vernaison is praised for its eclectic mix; the Marché Biron for higher-end antiques.",
    reviews: [
      { id: "pso-r1", author: "Dominique R.", rating: 5, text: "Could spend days here. Found an incredible art deco lamp for €40 after patient bargaining. A true Parisian institution.", date: "2025-04-05", initials: "DR" },
      { id: "pso-r2", author: "Maya K.", rating: 4, text: "Extraordinary range. Wear comfortable shoes, bring cash and allocate a full day. Don't miss Vernaison.", date: "2025-03-15", initials: "MK" },
      { id: "pso-r3", author: "Ethan B.", rating: 4, text: "The antiques quality is genuinely exceptional in the covered markets. The open-air section is more touristy but still fun.", date: "2025-02-01", initials: "EB" },
    ],
  },
];
